---
id: Idna
name: Idna
full: IDNA normalization library
description: >
  Normalized access to various backends providing IDNA (Internationalized Domain
  Names in Applications) support.
list: dev
type: library
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: true
    role: lead
version:
  release: 1.1.2
  api: 1.1.0
state:
  release: stable
  api: stable
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Util: ^2
  optional:
    ext:
      intl: '*'
